    version: "3"
    services:
      client:
        image: "dannycanuto/multi-client"
        mem_limit: 128m
        hostname: client
      server:
        image: "dannycanuto/multi-server"
        mem_limit: 128m
        hostname: api
        environment:
          - REDIS_HOST=$REDIS_HOST
          - REDIS_PORT=$REDIS_PORT
          - PGUSER=$PGUSER
          - PGHOST=$PGHOST
          - PGDATABASE=$PGDATABASE
          - PGPASSWORD=$PGPASSWORD
          - PGPORT=$PGPORT
      worker:
        image: "dannycanuto/multi-worker"
        mem_limit: 128m
        hostname: worker
        environment:
          - REDIS_HOST=$REDIS_HOST
          - REDIS_PORT=$REDIS_PORT
      nginx:
        image: "dannycanuto/multi-nginx"
        mem_limit: 128m
        hostname: nginx
        ports:
          - "80:80"